### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ghost** [Bara20/PHP-ServerViewer#2]
I did the whole installation process, but it is giving the following error:
```
Warning: mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50173 Library:50312 in /home/u109903972/public_html/status/index.php on line 59

Warning: mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50173 Library:50312 in /home/u109903972/public_html/status/index.php on line 232
```
What can be and how to correct?

**Comment by Bara** [comment]
That should nothing to do with the serverviewer.

[How about google?](https://www.google.de/search?q=mysqli()%3A+Headers+and+client+library+minor+version+mismatch.)

**Comment by ghost** [comment]
Ok
